# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca43977dcf5efcb0aca6bd3627e599d3c793db35248fe75e321b7c8f4097fd373c9d8556307639800d4995c7b7f6f8441031c081cabc3cce69265058d4647cef

test:
  secret_key_base: 572e5987db9755c569d5531a58ddd7b0b35a6fb97a49cdaa07a0a8a6ef71cde6c454a89fd70f1d4fc716140454060c360f5c596a532d2899a031744c614ebfe4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
